apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aether-ui-dashboard
  name: aether-ui-dashboard
spec:
  ports:
  - name: aether-ui-dashboard
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    run: aether-ui-dashboard
  type: NodePort
status:
  loadBalancer: {}
